version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6334:6333"
    volumes:
      - ./qdrant_collections/collections:/qdrant/storage/collections  # монтируем локальную папку коллекций
    environment:
      - QDRANT_HTTP_PORT=6333 
      - QDRANT_GRPC_PORT=6335
    networks:
      - qdrant-network

  flask-app:
    build: .
    container_name: flask
    ports:
      - "5000:5000"
    volumes:
      - .:/app 
    environment:
      - FLASK_APP=app.app:create_app
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - qdrant
    command: flask run --host=0.0.0.0
    networks:
      - qdrant-network

networks:
  qdrant-network:
    driver: bridge
